language: go
go:
  - 1.18
  - 1.19
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - make tools

script:
  - make ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
