GOFMT ?= gofmt -s -w
GOFILES := $(shell find . -name "*.go" -type f)

.PHONY: build
build: fmt
	go build -o mir-examples main.go

.PHONY: generate
generate:
	cd mirc
	-rm -rf gen
	go generate mirc/main.go
	cd ..

.PHONY: fmt
fmt:
	$(GOFMT) $(GOFILES)
