// Code generated by 'entc generate'. DO NOT EDIT.

//go:build generate && mirc
// +build generate,mirc

package main

import (
	"log"

	. "github.com/alimy/mir/v4/core"
	. "github.com/alimy/mir/v4/engine"
	"github.com/gin-gonic/gin"

	s1 "github.com/alimy/mir/mir-example/v4/mirc/routes"
	s2 "github.com/alimy/mir/mir-example/v4/mirc/routes/v1"
	s3 "github.com/alimy/mir/mir-example/v4/mirc/routes/v2"
	s4 "github.com/alimy/mir/mir-example/v4/mirc/routes/v3"
)

const conf = `{"SinkPath":"auto"}`

var entries = []any{
	&s1.Site{},
	&s2.Site{},
	&s2.Admin{},
	&s3.Site{},
	&s4.Site{},
}

func main() {
	if err := Generate(
		WithConf(conf),
		WithEntry(entries...),
		AssertType[*gin.Context](),
	); err != nil {
		log.Fatal(err)
	}
}
