// Code generated by 'mirc generate'. DO NOT EDIT.

//go:build mirc
// +build mirc

package main

import (
	"log"

	. "github.com/alimy/mir/v4/core"
	. "github.com/alimy/mir/v4/engine"
	"github.com/gin-gonic/gin"

	routes "github.com/alimy/mir/mir-example/v4/mirc/routes"
	v1 "github.com/alimy/mir/mir-example/v4/mirc/routes/v1"
	v2 "github.com/alimy/mir/mir-example/v4/mirc/routes/v2"
	v3 "github.com/alimy/mir/mir-example/v4/mirc/routes/v3"
)

const conf = `{"SinkPath":"auto"}`

var entries = []any{
	routes.Site{},
	v1.Site{},
	v1.Admin{},
	v2.Site{},
	v3.Site{},
}

func main() {
	if err := Generate(
		WithConf(conf),
		WithEntry(entries...),
		AssertType[*gin.Context](),
	); err != nil {
		log.Fatal(err)
	}
}
