// Code generated by go-mir. DO NOT EDIT.

package api

import (
	"net/http"

	gin "github.com/gin-gonic/gin"
)

type Site interface {
	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	Index(*gin.Context)
	Articles(*gin.Context)
}

// RegisterSiteServant register Site servant to gin
func RegisterSiteServant(e *gin.Engine, s Site) {
	router := e
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("GET", "/index/", s.Index)
	router.Handle("GET", "/articles/:category/", s.Articles)
}

// UnimplementedSiteServant can be embedded to have forward compatible implementations.
type UnimplementedSiteServant struct {
}

func (*UnimplementedSiteServant) Chain() gin.HandlersChain {
	return nil
}

func (*UnimplementedSiteServant) Index(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method Index not implemented")
}

func (*UnimplementedSiteServant) Articles(c *gin.Context) {
	c.String(http.StatusNotImplemented, "method Articles not implemented")
}
